algoritmo "semnome"
// Função :
// Autor :
// Data : 11/03/2013
// Seção de Declarações 
var
n1: inteiro
inicio
escreva ("Entre com o valor a ser testado: ")
leia (n1)
escolha (n1)
caso 1
     escreval ("O valor introduzido é 1")
caso 5
     escreval ("O valor introduzido é 5")
caso 10
     escreval ("O valor introduzido é 10")
outrocaso
     escreval ("Valor Inválido:", n1)
     fimescolha
// Seção de Comandos 
fimalgoritmo
