algoritmo "semnome"
// Função :
// Autor :
// Data : 11/03/2013
// Seção de Declarações 
var
idade: inteiro
passagem: real
inicio
escreval ("Por favor, insira o valor da sua passagem:")
leia (passagem)
escreval ("Agora, insira a sua idade em anos:")
leia (idade)
se (idade>=65) entao
   escreval ("Sua passagem é garantida por lei e não será cobrado.")
senao
     escreval ("Sua passagem custará: R$", passagem:2:2)
   fimse
   escreval ("Obrigado.")
// Seção de Comandos 
fimalgoritmo
